language: csharp
dist: trusty
sudo: false
mono: none
dotnet: 2.1
branches:
  only:
  - master
before_install:
- sudo apt-get update
- sudo apt-get install -y clang-3.9 libcurl3-dev zlib1g-dev libkrb5-dev libsdl2-2.0-0
script:
- dotnet restore
- dotnet build
- dotnet publish -r linux-x64 -c release
before_deploy:
- git config --local user.name "Diogo Gomes"
- git config --local user.email "dgomes@graphnode.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: GTHtUlFs0YjSNgr+e6TkHAPskRAPuj3wLrEk5zbCjQTV/Oh2VsUnWBSAiYp7Vc+iSpHaxtHkx26zOu5kc1kbmfrMfzTkIljRqZEDJXJOH4oJhyMuYp0oaX7yI8VdvrCZkTVKaLUXdCN8OzRfIIDF6UfESLqu+/rFM5PYT9aQuEMOHhWdbYLDk7WQuXUYWlMafvemWV0ywWLd2K/ujmtXwgDMrVs/Ebb0CF7OEIcX/5zBOiTYLqq/iubwt2emr2mDY4z4KE9OCuTIt0yHu1TNEAAC7t6xG6JEu9WLO1g8uSMderNTdFdZTgRTnvBtqf04odp173/H3I4QtRF3YfoO7zcgbYmj38ArvamCtnbMylk/FhfrgNRBt6/B+4M+I1I0KQvZFNkO+RW7h/DeSmw9uB0giwO0BBl5OyTFfujgxPCED2+AqmZoFvvl+QCtAMH6RidbnqrhHJWRJEcCQwT9CBqxyUuQdUrDG7b90kNHcx6ad0PkrioNHkST4o12rm51QsVdiqBIRJQXRAJgZajJ18vPbtLGPtVJZakMV/0C643UcwPEGQWOKlasFjRITJBrTApOlKroePAKz637LC7Cj8bdKAbVaSqFmyFeeV6ILpE6r/zyjWc9x8G0W5toZXVo9m+F3q/5vS/XtejvW/xmPSVp4o6PbEunD5RQvlOC+dw=
  file_glob: true
  file: bin/release/netcoreapp2.1/linux-x64/publish/*
  on:
    repo: graphnode/HelloCI
