version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017
build_script:
- sh: >-
    dotnet restore

    dotnet build

    dotnet publish -r win-x64 -c release


    cd bin\release\netcoreapp2.1\win-x64\publish\

    7z.exe a "helloci-$(date +%Y%m%d)-$(git log --format=%h -1)-win64.zip" .
artifacts:
- path: bin\release\netcoreapp2.1\win-x64\publish\*.zip
  name: HelloCI
deploy:
- provider: GitHub
  tag: ${APPVEYOR_REPO_TAG_NAME}
  auth_token:
    secure: qpEdvpJkR5kaDAqw5g/z7chnKwqLqaMYW1/yFazttmxXyBbZqxPUSPjOeexjo7uh
  repository: graphnode/HelloCI
  draft: false
  prerelease: false
  force_update: true
