version: 'pending-{build}'
branches:
  only:
  - master
skip_tags: true
image: 
- Visual Studio 2017
- Ubuntu
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      runtime_id: win-x64
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      runtime_id: linux-x64
init:
- pwsh: Update-AppveyorBuild -Version "$(Get-Date -format yyyyMMdd)-$($env:appveyor_repo_commit.substring(0,7))"
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(APPVEYOR_BUILD_VERSION)
  package_version: $(APPVEYOR_BUILD_VERSION)
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  file_version: $(APPVEYOR_BUILD_VERSION)
  informational_version: $(APPVEYOR_BUILD_VERSION)
build_script:
- pwsh: >-
    dotnet restore

    dotnet build

    dotnet publish -r $env:runtime_id -c release
after_build:
- pwsh: >-
    cd bin\release\netcoreapp2.1\$($env:runtime_id)\publish\

    7za a "helloci-$($env:appveyor_build_version)-$($env:runtime_id).zip" .
test: off
artifacts:
- path: bin\release\netcoreapp2.1\win-x64\publish\helloci-$(APPVEYOR_BUILD_VERSION)-$(runtime_id).zip
  name: HelloCI
deploy:
- provider: GitHub
  tag: $(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: qpEdvpJkR5kaDAqw5g/z7chnKwqLqaMYW1/yFazttmxXyBbZqxPUSPjOeexjo7uh
  repository: graphnode/HelloCI
  draft: false
  prerelease: false
  force_update: false
  on:
    branch: master    
