version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017
init:
- ps: Update-AppveyorBuild -Version "$(Get-Date -format yyyyMMdd)-$(git rev-parse --short $env:APPVEYOR_REPO_COMMIT)"
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(APPVEYOR_BUILD_VERSION)
  package_version: $(APPVEYOR_BUILD_VERSION)
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  file_version: $(APPVEYOR_BUILD_VERSION)
  informational_version: $(APPVEYOR_BUILD_VERSION)
build_script:
- sh: >-
    dotnet restore

    dotnet build

    dotnet publish -r win-x64 -c release


    cd bin\release\netcoreapp2.1\win-x64\publish\

    7z.exe a "helloci-$(date +%Y%m%d)-$(git log --format=%h -1)-win64.zip" .
test: off
artifacts:
- path: bin\release\netcoreapp2.1\win-x64\publish\*.zip
  name: HelloCI
deploy:
- provider: GitHub
  tag: $(date +%Y%m%d)-$(git log --format=%h -1)
  auth_token:
    secure: qpEdvpJkR5kaDAqw5g/z7chnKwqLqaMYW1/yFazttmxXyBbZqxPUSPjOeexjo7uh
  repository: graphnode/HelloCI
  draft: false
  prerelease: false
  force_update: true