version: 'pending-{build}'

branches:
  only:
  - master

skip_tags: true

image: 
- Visual Studio 2017
- Ubuntu

environment:  
  APPVEYOR_YML_DISABLE_PS_LINUX: true

init:
- ps: Update-AppveyorBuild -Version "$(Get-Date -format yyyyMMdd)-$($env:appveyor_repo_commit.substring(0,7))"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(APPVEYOR_BUILD_VERSION)
  package_version: $(APPVEYOR_BUILD_VERSION)
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  file_version: $(APPVEYOR_BUILD_VERSION)
  informational_version: $(APPVEYOR_BUILD_VERSION)
  
before_build:
- sh: >-
    sudo apt-get update
    
    sudo apt-get install -y clang-3.9 libcurl3-dev zlib1g-dev libkrb5-dev

build_script:
- ps: >-
    dotnet restore

    dotnet build

    dotnet publish -r win-x64 -c release
- sh: >-
    dotnet restore

    dotnet build

    dotnet publish -r linux-x64 -c release
    
after_build:
- ps: >-
    cd $env:appveyor_build_folder\bin\release\netcoreapp2.1\win-x64\publish\

    7z.exe a "helloci-$($env:appveyor_build_version)-win-x64.zip" .
    
    Push-AppveyorArtifact "helloci-$($env:appveyor_build_version)-win-x64.zip"
    
- sh: >-
    cd $APPVEYOR_BUILD_FOLDER/bin/release/netcoreapp2.1/linux-x64/publish/

    7za a "helloci-$APPVEYOR_BUILD_VERSION-linux-x64.zip" .
    
    appveyor PushArtifact "helloci-$APPVEYOR_BUILD_VERSION-linux-x64.zip"

test_script:
- ps: "cd $env:appveyor_build_folder\\bin\\release\\netcoreapp2.1\\win-x64\\publish\\\n\nHelloCI.exe\n    \nif ($LastExitCode -eq 0) {\n    Add-AppveyorTest -Name \"Executing\" -Framework None -Filename HelloCI.exe -Outcome Passed\n} else {\n    Add-AppveyorTest -Name \"Executing\" -Framework None -Filename HelloCI.exe -Outcome Failed\n}"

    
- sh: >-
    cd $APPVEYOR_BUILD_FOLDER/bin/release/netcoreapp2.1/linux-x64/publish/


    ./HelloCI


    if [ $? -eq 0 ]

    then
       appveyor AddTest "Executing" -Framework None -Filename HelloCI.exe -Outcome Passed
    else
       appveyor AddTest "Executing" -Framework None -Filename HelloCI.exe -Outcome Failed
    fi
    
deploy:
- provider: GitHub
  tag: $(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: qpEdvpJkR5kaDAqw5g/z7chnKwqLqaMYW1/yFazttmxXyBbZqxPUSPjOeexjo7uh
  repository: graphnode/HelloCI
  draft: false
  prerelease: false
  force_update: false
  on:
    branch: master    
