version: 'pending-{build}'
branches:
  only:
  - master
skip_tags: true
image: 
- Visual Studio 2017
- Ubuntu
environment:  
  APPVEYOR_YML_DISABLE_PS_LINUX: true
init:
- ps: Update-AppveyorBuild -Version "$(Get-Date -format yyyyMMdd)-$($env:appveyor_repo_commit.substring(0,7))"
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(APPVEYOR_BUILD_VERSION)
  package_version: $(APPVEYOR_BUILD_VERSION)
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  file_version: $(APPVEYOR_BUILD_VERSION)
  informational_version: $(APPVEYOR_BUILD_VERSION)
  
before_build:
- sh: >-
    sudo apt-get update
    
    sudo apt-get install -y clang-3.9 libcurl3-dev zlib1g-dev libkrb5-dev

build_script:
- ps: >-
    dotnet restore

    dotnet build

    dotnet publish -r win-x64 -c release
- sh: >-
    dotnet restore

    dotnet build

    dotnet publish -r linux-x64 -c release
    
after_build:
- ps: >-
    cd bin\release\netcoreapp2.1\win-x64\publish\

    7z.exe a "helloci-$($env:appveyor_build_version)-win-x64.zip" .
- sh: >-
    cd bin/release/netcoreapp2.1/linux-x64/publish/

    7za a "helloci-$(APPVEYOR_BUILD_VERSION)-linux-x64.zip" .
    
test: off
artifacts:
- path: bin\release\netcoreapp2.1\*\publish\helloci-$(APPVEYOR_BUILD_VERSION)-*.zip
  name: HelloCI
deploy:
- provider: GitHub
  tag: $(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: qpEdvpJkR5kaDAqw5g/z7chnKwqLqaMYW1/yFazttmxXyBbZqxPUSPjOeexjo7uh
  repository: graphnode/HelloCI
  draft: false
  prerelease: false
  force_update: false
  on:
    branch: master    
