version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: ${APPVEYOR_REPO_TAG_NAME}
  package_version: ${APPVEYOR_REPO_TAG_NAME}
  assembly_version: ${APPVEYOR_REPO_TAG_NAME}
  file_version: ${APPVEYOR_REPO_TAG_NAME}
  informational_version: ${APPVEYOR_REPO_TAG_NAME}
build_script:
- cmd: >-
    dotnet restore

    dotnet build

    dotnet publish -r win-x64 -c release


    cd bin\release\netcoreapp2.1\win-x64\publish\

    7z.exe a helloci-${APPVEYOR_REPO_TAG_NAME}-win64.zip .
artifacts:
- path: bin\release\netcoreapp2.1\win-x64\publish\helloci-${APPVEYOR_REPO_TAG_NAME}-win64.zip
  name: HelloCI
deploy:
- provider: GitHub
  auth_token:
    secure: qpEdvpJkR5kaDAqw5g/z7chnKwqLqaMYW1/yFazttmxXyBbZqxPUSPjOeexjo7uh
  repository: graphnode/HelloCI
  draft: false
  prerelease: false